-- Conectar ao contêiner raiz
ALTER SESSION SET CONTAINER = CDB$ROOT;

-- Habilitar log suplementar (caso ainda não esteja ativo)
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- Verificar se o modo ARCHIVELOG já está ativado
SELECT LOG_MODE FROM V$DATABASE;

-- Se ARCHIVELOG não estiver ativado, será necessário reiniciar o banco:
-- SHUTDOWN IMMEDIATE;
-- STARTUP MOUNT;
-- ALTER DATABASE ARCHIVELOG;
-- ALTER DATABASE OPEN;

-- Criar usuário comum para CDC no contêiner raiz
CREATE USER C##cdc_user IDENTIFIED BY cdc_password CONTAINER=ALL;

-- Conceder permissões básicas
GRANT CONNECT, RESOURCE TO C##cdc_user CONTAINER=ALL;
GRANT CREATE SESSION, SELECT ANY TABLE TO C##cdc_user CONTAINER=ALL;

-- Conceder permissões específicas para LogMiner
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES TO C##cdc_user CONTAINER=ALL;
GRANT LOGMINING TO C##cdc_user CONTAINER=ALL;

-- Conceder permissões adicionais para acessar logs e transações
GRANT EXECUTE_CATALOG_ROLE TO C##cdc_user CONTAINER=ALL;
GRANT ALTER SESSION TO C##cdc_user CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##cdc_user CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##cdc_user CONTAINER=ALL;

-- Garantir que o usuário possa armazenar dados na tablespace USERS
ALTER USER C##cdc_user QUOTA UNLIMITED ON USERS;

-- Voltar para o banco de dados pluggable
ALTER SESSION SET CONTAINER = XEPDB1;

-- Conceder as mesmas permissões no PDB
GRANT CONNECT, RESOURCE TO C##cdc_user;
GRANT CREATE SESSION, SELECT ANY TABLE TO C##cdc_user;
GRANT SELECT ON V_$LOG TO C##cdc_user;
GRANT SELECT ON V_$DATABASE TO C##cdc_user;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##cdc_user;
GRANT SELECT ON V_$LOGFILE TO C##cdc_user;
GRANT SELECT ON V_$INSTANCE TO C##cdc_user;
GRANT SELECT ON V_$THREAD TO C##cdc_user;
GRANT SELECT ON DBA_REGISTRY TO C##cdc_user;
GRANT EXECUTE_CATALOG_ROLE TO C##cdc_user;
GRANT ALTER SESSION TO C##cdc_user;
GRANT SELECT_CATALOG_ROLE TO C##cdc_user;
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##cdc_user;
GRANT SELECT ANY TRANSACTION TO C##cdc_user;
GRANT SELECT ANY DICTIONARY TO C##cdc_user;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##cdc_user;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##cdc_user;
GRANT SELECT ON V_$PARAMETER TO C##cdc_user;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##cdc_user;
GRANT SELECT ON V_$TIMEZONE_NAMES TO C##cdc_user;
GRANT LOGMINING TO C##cdc_user;
